AWSTemplateFormatVersion: 2010-09-09

Description: Zonumi Website

Parameters:

  VpcName:
    Type: String
    Description: Name of the VPC to deploy into

  Name:
    Type: String
    Description: Name of the service
    Default: zonumi-website

  ContainerPort:
    Type: Number
    Description: Port to image inside the container will be listening on
    Default: 3000

  ImageVersion:
    Type: String
    Description: Version of the application image (placeholder will be replaced in CI)
    Default: VERSION_PLACEHOLDER

  DesiredCount:
    Type: Number
    Description: Desired number of running tasks
    Default: 2

Resources:

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Ref Name
          Environment:
            - Name: Name
              Value: !Ref Name
            - Name: VpcName
              Value: !Ref VpcName
          Essential: true
          Image: !Sub 573536211534.dkr.ecr.eu-west-2.amazonaws.com/${Name}:${ImageVersion}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref Name
          DisableNetworking: false
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          ReadonlyRootFilesystem: false
      Cpu: 512
      ExecutionRoleArn: 'arn:aws:iam::573536211534:role/ecsTaskExecutionRole'
      Family: !Join [ '-', [ !Ref VpcName, !Ref Name ] ]
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - Listener
    Properties:
      Cluster: !ImportValue
        Fn::Sub: ${VpcName}-EcsCluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      PlatformVersion: 1.4.0
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Split
            - ','
            - !ImportValue
              Fn::Sub: ${VpcName}-PrivateSubnets
          SecurityGroups:
            - !ImportValue
              Fn::Sub: ${VpcName}-ServiceSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref Name
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        [{ 'Fn::ImportValue': !Sub '${VpcName}-RestrictedElbSecurityGroup' }]
      Subnets:
        !Split [',', { 'Fn::ImportValue': !Sub '${VpcName}-PublicSubnets'}]
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: true
        - Key: access_logs.s3.bucket
          Value: !ImportValue
            Fn::Sub: ${VpcName}-LogsBucket

  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    DependsOn:
      - LoadBalancer
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: !ImportValue
        Fn::Sub: ${VpcName}-VpcId
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${VpcName}-${Name}
      RetentionInDays: 7

